import { CARD_MAP } from "../../data/cards.js";

const FALLBACK_DECK_CARDS = [
  "rattata", "rattata", "pidgey", "pidgey", "quickattack", "potion", "pokeball",
];

function makeDeck(pool, size = 30) {
  const valid = pool.filter((id) => CARD_MAP[id]);
  const source = valid.length
    ? valid
    : FALLBACK_DECK_CARDS.filter((id) => CARD_MAP[id]);
  const deck = [];
  if (!source.length) return deck;
  while (deck.length < size) deck.push(source[deck.length % source.length]);
  return deck;
}

export const ENCOUNTERS = [
  {
    id: "rogue_rocket_grunt",
    faction: "로켓단",
    name: "로켓단 조무래기",
    title: "로켓단 · 침투전",
    sprite: "rocketgrunt",
    aiLevel: 2,
    hp: 30,
    reward: 0,
    introLines: ["여긴 로켓단의 구역이다! 가진 포켓몬을 전부 내놔!"],
    winLines: ["흥! 역시 로켓단의 힘이지!"],
    loseLines: ["뭐야, 이런 녀석에게 지다니...!"],
    deck: makeDeck([
      "rattata", "raticate", "zubat", "golbat", "ekans", "arbok", "grimer", "muk",
      "quickattack", "toxic", "pokeball", "potion",
    ]),
  },
  {
    id: "rogue_rocket_proton",
    faction: "로켓단",
    name: "로켓단 간부 랜스",
    title: "로켓단 · 발전소 습격",
    sprite: "proton",
    aiLevel: 3,
    hp: 34,
    reward: 0,
    introLines: ["방해꾼이 하나 들어왔군. 빠르게 처리하지."],
    winLines: ["이 정도 속도도 못 따라오나?"],
    loseLines: ["칫... 생각보다 제법이군."],
    deck: makeDeck([
      "zubat", "golbat", "koffing", "weezing", "voltorb", "electrode",
      "rattata", "raticate", "thunderbolt", "toxic", "quickattack", "superball", "potion",
    ]),
  },
  {
    id: "rogue_rocket_petrel",
    faction: "로켓단",
    name: "로켓단 간부 람다",
    title: "로켓단 · 위장 작전",
    sprite: "petrel",
    aiLevel: 3,
    hp: 38,
    reward: 0,
    introLines: ["진짜와 가짜를 구분할 수 있을까? 이미 늦었지만 말이야!"],
    winLines: ["속임수도 실력이라고!"],
    loseLines: ["이 얼굴까지 들켰다고...?"],
    deck: makeDeck([
      "koffing", "weezing", "grimer", "muk", "houndour", "houndoom",
      "zubat", "golbat", "toxic", "darkpulse", "flamethrower", "superball", "potion",
    ]),
  },
  {
    id: "rogue_rocket_athena",
    faction: "로켓단",
    name: "로켓단 간부 아테나",
    title: "로켓단 · 간부전",
    sprite: "ariana",
    aiLevel: 4,
    hp: 42,
    reward: 0,
    introLines: ["조무래기들을 이겼다고 우쭐대지 마. 간부의 싸움은 다르니까."],
    winLines: ["이게 로켓단 간부의 실력이야."],
    loseLines: ["비주기 님께서 그냥 두지 않으실 거야...!"],
    deck: makeDeck([
      "arbok", "gloom", "vileplume", "murkrow", "honchkrow", "zubat", "golbat", "crobat",
      "stunky", "skuntank", "darkpulse", "toxic", "superball", "fullrestore",
    ]),
  },
  {
    id: "rogue_rocket_archer",
    faction: "로켓단",
    name: "로켓단 간부 아폴로",
    title: "로켓단 · 최종 간부전",
    sprite: "archer",
    aiLevel: 4,
    hp: 47,
    reward: 0,
    introLines: ["여기까지 온 건 인정하지. 하지만 비주기 님께 닿게 할 수는 없다."],
    winLines: ["로켓단의 재건은 막을 수 없다."],
    loseLines: ["비주기 님... 죄송합니다."],
    deck: makeDeck([
      "houndour", "houndoom", "koffing", "weezing", "golbat", "crobat",
      "magmar", "raticate", "darkpulse", "flamethrower", "toxic", "focussash", "fullrestore",
    ]),
  },
  {
    id: "rogue_giovanni",
    faction: "로켓단",
    name: "로켓단 보스 비주기",
    title: "로켓단 · 조직 보스",
    sprite: "giovanni",
    aiLevel: 5,
    hp: 54,
    reward: 0,
    introLines: ["조직을 무너뜨리겠다고? 힘이 무엇인지 직접 가르쳐 주지."],
    winLines: ["결국 힘 앞에서는 모두 무릎을 꿇는다."],
    loseLines: ["흥미롭군. 하지만 이것으로 끝이라고 생각하지 마라."],
    deck: makeDeck([
      "persian", "rhyhorn", "rhydon", "rhyperior", "nidorino", "nidoking",
      "nidorina", "nidoqueen", "diglett", "dugtrio", "sandile", "krokorok", "krookodile",
      "earthquake", "stoneedge", "sandstorm", "hyperball", "fullrestore", "focussash",
    ]),
  },
  {
    id: "rogue_galactic_grunt",
    faction: "갤럭시단",
    name: "갤럭시단 조무래기",
    title: "갤럭시단 · 기지 침입",
    sprite: "galacticgrunt",
    aiLevel: 3,
    hp: 40,
    reward: 0,
    introLines: ["우주의 새 질서를 방해하는 녀석은 전부 제거한다!"],
    winLines: ["갤럭시단의 계획은 완벽하다!"],
    loseLines: ["간부님들이 가만두지 않을 거야!"],
    deck: makeDeck([
      "zubat", "golbat", "glameow", "purugly", "stunky", "skuntank",
      "bronzor", "quickattack", "toxic", "reflect", "superball", "potion",
    ]),
  },
  {
    id: "rogue_galactic_mars",
    faction: "갤럭시단",
    name: "갤럭시단 간부 마스",
    title: "갤럭시단 · 마스",
    sprite: "mars",
    aiLevel: 4,
    hp: 46,
    reward: 0,
    introLines: ["여기까지 들어오다니 배짱은 있네. 그럼 내가 직접 상대해 줄게!"],
    winLines: ["갤럭시단의 계획은 멈추지 않아!"],
    loseLines: ["말도 안 돼... 태홍 님께 보고해야 해!"],
    deck: makeDeck([
      "zubat", "golbat", "crobat", "glameow", "purugly", "stunky", "skuntank",
      "bronzor", "bronzong", "darkpulse", "toxic", "reflect", "superball", "fullrestore",
    ]),
  },
  {
    id: "rogue_galactic_jupiter",
    faction: "갤럭시단",
    name: "갤럭시단 간부 주피터",
    title: "갤럭시단 · 주피터",
    sprite: "jupiter",
    aiLevel: 4,
    hp: 50,
    reward: 0,
    introLines: ["마스를 이겼다고? 그럼 내가 조금 더 진지하게 상대해 주지."],
    winLines: ["이 정도 차이도 모르는 건가?"],
    loseLines: ["흥... 아직 새턴이 남아 있어."],
    deck: makeDeck([
      "stunky", "skuntank", "zubat", "golbat", "crobat", "bronzor", "bronzong",
      "murkrow", "honchkrow", "toxic", "darkpulse", "lightscreen", "focussash", "fullrestore",
    ]),
  },
  {
    id: "rogue_galactic_saturn",
    faction: "갤럭시단",
    name: "갤럭시단 간부 새턴",
    title: "갤럭시단 · 새턴",
    sprite: "saturn",
    aiLevel: 5,
    hp: 55,
    reward: 0,
    introLines: ["우리의 이상을 이해하지 못한다면 힘으로 비켜 세울 수밖에."],
    winLines: ["태홍 님의 우주에는 불필요한 것이 없다."],
    loseLines: ["이 힘이라면... 태홍 님께서 직접 나서실 수밖에 없겠군."],
    deck: makeDeck([
      "croagunk", "toxicroak", "golbat", "crobat", "bronzor", "bronzong",
      "abra", "kadabra", "alakazam", "toxic", "psychic", "reflect", "lightscreen", "fullrestore",
    ]),
  },
  {
    id: "rogue_galactic_cyrus",
    faction: "갤럭시단",
    name: "갤럭시단 보스 태홍",
    title: "갤럭시단 · 새로운 우주",
    sprite: "cyrus",
    aiLevel: 5,
    hp: 62,
    reward: 0,
    introLines: ["불완전한 마음이 존재하는 한 이 세계는 완성되지 않는다. 사라져라."],
    winLines: ["감정에 매달리는 자는 결국 무너진다."],
    loseLines: ["이 세계의 불완전함을... 네가 증명했다는 건가."],
    deck: makeDeck([
      "murkrow", "honchkrow", "zubat", "golbat", "crobat", "sneasel", "weavile",
      "magikarp", "gyarados", "houndour", "houndoom", "darkpulse", "hydropump",
      "reflect", "lightscreen", "focussash", "fullrestore",
    ]),
  },
  {
    id: "rogue_plasma_grunt",
    faction: "플라즈마단",
    name: "플라즈마단 조무래기",
    title: "플라즈마단 · 성 내부",
    sprite: "plasmagrunt-gen5bw",
    aiLevel: 4,
    hp: 46,
    reward: 0,
    introLines: ["포켓몬을 해방하기 위해 너의 포켓몬부터 빼앗겠다!"],
    winLines: ["이것이 포켓몬 해방을 위한 정의다!"],
    loseLines: ["우리가 틀렸다는 건가...?"],
    deck: makeDeck([
      "patrat", "watchog", "purrloin", "liepard", "sandile", "krokorok",
      "yamask", "cofagrigus", "vullaby", "mandibuzz", "darkpulse", "toxic", "superball", "potion",
    ]),
  },
  {
    id: "rogue_plasma_elite",
    faction: "플라즈마단",
    name: "플라즈마단 정예병",
    title: "플라즈마단 · 친위대",
    sprite: "plasmagruntf-gen5bw",
    aiLevel: 5,
    hp: 54,
    reward: 0,
    introLines: ["게치스 님께 가까이 갈 생각이라면 여기서 끝내 주지."],
    winLines: ["플라즈마단의 힘은 이 정도가 아니다."],
    loseLines: ["아크로마 님께서 네 힘을 분석하실 것이다."],
    deck: makeDeck([
      "lillipup", "herdier", "stoutland", "sandile", "krokorok", "krookodile",
      "pawniard", "bisharp", "vullaby", "mandibuzz", "ferroseed", "ferrothorn",
      "darkpulse", "reflect", "lightscreen", "focussash", "fullrestore",
    ]),
  },
  {
    id: "rogue_colress",
    faction: "플라즈마단",
    name: "플라즈마단 아크로마",
    title: "플라즈마단 · 포켓몬의 가능성",
    sprite: "colress",
    aiLevel: 5,
    hp: 62,
    reward: 0,
    introLines: ["포켓몬의 힘을 최대한 끌어내는 조건... 네 전투로 검증해 보겠습니다."],
    winLines: ["역시 데이터가 말해 주는군요."],
    loseLines: ["훌륭합니다. 이런 결과는 예상 범위를 넘어섰군요."],
    deck: makeDeck([
      "magnemite", "magneton", "magnezone", "beldum", "metang", "metagross",
      "porygon", "porygon2", "porygonz", "rotom", "ferroseed", "ferrothorn",
      "thunderbolt", "reflect", "lightscreen", "focussash", "fullrestore",
    ]),
  },
  {
    id: "rogue_ghetsis",
    faction: "플라즈마단",
    name: "플라즈마단 게치스",
    title: "악의 조직 소탕 · 최종전",
    sprite: "ghetsis-gen5bw",
    aiLevel: 5,
    hp: 72,
    reward: 0,
    introLines: ["포켓몬을 다루는 자들 위에 서는 것은 오직 나다. 네 여정도 여기까지다!"],
    winLines: ["모든 것은 나의 계획대로다!"],
    loseLines: ["내가... 내가 이런 곳에서 패배한다고?!"],
    deck: makeDeck([
      "deino", "zweilous", "hydreigon", "yamask", "cofagrigus", "druddigon", "haxorus",
      "vullaby", "mandibuzz", "sandile", "krokorok", "krookodile", "pawniard", "bisharp",
      "dragontail", "darkpulse", "reflect", "lightscreen", "focussash", "fullrestore", "hyperball",
    ]),
  },
];
